table 'public fato_apuracao'
	lineageTag: c09012f7-414e-40f3-aba7-c9fdaf821b51

	measure '4Horas Absenteismo' =
			
			DIVIDE(
			    SUMX(
			        SUMMARIZE(
			            FILTER(
			                'public fato_apuracao',
			                'public fato_apuracao'[flag_absenteismo] = "Sim"
			                    && 'public fato_apuracao'[id_cod_empresa] IN {1,2,5}
			                    && 'public fato_apuracao'[id_tipo_colaborador] IN {1,2}
			                    && 'public fato_apuracao'[data_apuracao] >= DATE(2025,1,1)
			            ),
			            'public fato_apuracao'[sk_colaborador],
			            'public fato_apuracao'[data_apuracao],
			            'public fato_apuracao'[id_situacao_apuracao],
			            'public fato_apuracao'[quantidade_horas_minutos]
			        ),
			        'public fato_apuracao'[quantidade_horas_minutos]
			    ),
			    60,
			    0
			)
		lineageTag: c93c0402-29bc-4e55-8029-74d1b63ce823

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '1Horas Trabalhadas' = ```
			
			DIVIDE(
			    CALCULATE(
			        SUM('public fato_apuracao'[quantidade_horas_minutos]),
			        'public fato_apuracao'[flag_absenteismo] = "Não",
			        'public fato_apuracao'[id_cod_empresa] = 1,
			        'public fato_apuracao'[id_tipo_colaborador] =1 ,
			        'public.dCalendario'[date] >= DATE(2025, 1, 1)
			    ),
			    2,
			    0
			)
			
			```
		lineageTag: 353f9948-9b7e-47dc-a64a-d905f7358817

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '1Horas Previstas semanas' = ```
			
			DIVIDE(
			    MAX('public dim_escala'[horas_prevista_semana]),
			    60
			)
			
			```
		lineageTag: 10750826-3702-4c40-bb54-0966a9835a5c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '1Diferença Horas medida' =
			
			[1Horas Trabalhadas] - [1Horas Previstas semanas 1]
		lineageTag: 12167953-2e13-4001-ada5-8dcf9b0a927b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '1Diferença Horas Formatada' =
			
			VAR MinutosTotais =
			    ROUND([1Diferença Horas medida] * 60, 0)
			VAR Sinal =
			    IF(MinutosTotais > 0, "+", IF(MinutosTotais < 0, "-", ""))
			VAR MinutosAbsolutos =
			    ABS(MinutosTotais)
			VAR Horas =
			    QUOTIENT(MinutosAbsolutos, 60)
			VAR Minutos =
			    MOD(MinutosAbsolutos, 60)
			RETURN
			    Sinal
			        & Horas
			        & "h "
			        & FORMAT(Minutos, "00")
			        & "m"
		lineageTag: 89b9b72f-a344-42f7-a25b-c51d5dfef3a4

	measure '1Taxa Absenteísmo' =
			
			DIVIDE(
			    [4Horas Absenteismo],
			    [1Horas Previstas semanas 1],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c83dd250-c416-40cb-a7d5-6d7c54706da3

	measure '1Horas Previstas1' =
			
			DIVIDE(
			    MAX('public dim_escala'[horas_prevista_semana]),
			    60
			)
		lineageTag: de311d22-c06e-4187-8619-453d335553e1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '4Diferença Horas medida mês' =
			
			[3Horas Trabalhadas Líquidas] - [4Horas Previstas Pessoa Mês]
		lineageTag: 01638ac1-d978-492f-a82e-eba7f1a3526b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '4Diferença Horas Formatada mês' =
			
			VAR MinutosTotais =
			    ROUND([4Diferença Horas medida mês] * 60, 0)
			VAR Sinal =
			    IF(MinutosTotais > 0, "+", IF(MinutosTotais < 0, "-", ""))
			VAR MinutosAbsolutos =
			    ABS(MinutosTotais)
			VAR Horas =
			    QUOTIENT(MinutosAbsolutos, 60)
			VAR Minutos =
			    MOD(MinutosAbsolutos, 60)
			RETURN
			    Sinal
			        & Horas
			        & "h "
			        & FORMAT(Minutos, "00")
			        & "m"
		lineageTag: 2667600d-f16f-48fc-88a6-f7f7f9bb2c79

	measure '2Taxa Absenteísmo mês' =
			
			DIVIDE(
			    [4Horas Absenteismo],
			    [2Horas Previstas mês3],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b730df85-22d0-4c68-9c65-3ba27cec6b63

	measure '2Horas Previstas mês3' =
			
			VAR CodigoEscalaAtual =
			    SELECTEDVALUE('public fato_apuracao'[codigo_escala])
			
			VAR MinutosPrevistos =
			    LOOKUPVALUE(
			        'public dim_escala'[total_hora_mes],
			        'public dim_escala'[codigo_escala],
			        CodigoEscalaAtual
			    )
			
			RETURN
			    DIVIDE(MinutosPrevistos, 60)
		lineageTag: a278f865-3860-46b5-9af2-4929f1acd096

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '2Horas Previstas mês' =
			
			DIVIDE(
			    SELECTEDVALUE(
			        'public dim_escala'[total_hora_mes]
			    ),
			    60
			)
		lineageTag: 4500e587-ada2-4507-91c2-11b3aeae6d62

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '1Horas Previstas semanas 1' =
			
			VAR CodigoEscalaAtual =
			    SELECTEDVALUE('public fato_apuracao'[codigo_escala])
			
			VAR MinutosPrevistos =
			    LOOKUPVALUE(
			        'public dim_escala'[horas_prevista_semana],
			        'public dim_escala'[codigo_escala],
			        CodigoEscalaAtual
			    )
			
			RETURN
			    DIVIDE(MinutosPrevistos, 60)
		lineageTag: 29b56f4c-d853-4d28-93af-354144b4152d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '4Salário Base Mensal' =
			
			SUMX(
			    SUMMARIZE(
			        'public fato_apuracao',
			        'public fato_apuracao'[cracha],
			        'public.dCalendario'[AnoMes],
			        "SalarioMes",
			            CALCULATE(
			                MAX('public fato_apuracao'[salario_base])
			            )
			    ),
			    [SalarioMes]
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: ec320743-5762-4841-9363-db6546d7982e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '4Horas Previstas Pessoa Mês' = VAR ColaboradoresMes = CALCULATETABLE( SUMMARIZE( 'public fato_apuracao', 'public fato_apuracao'[sk_colaborador], 'public.dCalendario'[AnoMes] ), 'public fato_apuracao'[id_cod_empresa] IN { 1, 2, 5 }, 'public fato_apuracao'[id_tipo_colaborador] IN { 1, 2 }, 'public.dCalendario'[date] >= DATE(2025, 1, 1), REMOVEFILTERS( 'public fato_apuracao'[flag_absenteismo] ), REMOVEFILTERS( 'public dim_situacao_apuracao' ) ) RETURN SUMX( ColaboradoresMes, VAR MinutosPrevistos = CALCULATE( MAXX( 'public fato_apuracao', RELATED( 'public dim_escala'[total_hora_mes] ) ), 'public fato_apuracao'[id_cod_empresa] IN { 1, 2, 5 }, 'public fato_apuracao'[id_tipo_colaborador] IN { 1, 2 }, REMOVEFILTERS( 'public fato_apuracao'[flag_absenteismo] ), REMOVEFILTERS( 'public dim_situacao_apuracao' ) ) RETURN DIVIDE(MinutosPrevistos, 60, 0) )
		lineageTag: 7fa5abae-9357-4d4d-89ac-35fa79f49b2e

	measure '4Horas Trabalhadas Líquidas' =
			
			VAR BaseSemDuplicidade =
			    FILTER(
			        SUMMARIZE(
			            'public fato_apuracao',
			            'public fato_apuracao'[data_apuracao],
			            'public fato_apuracao'[sk_colaborador],
			            'public fato_apuracao'[cracha],
			            'public fato_apuracao'[flag_absenteismo],
			            'public fato_apuracao'[id_situacao_apuracao],
			            'public dim_situacao_apuracao'[descricao_situacao],
			            'public fato_apuracao'[quantidade_horas_minutos],
			            'public fato_apuracao'[codigo_escala]
			        ),
			        'public fato_apuracao'[id_situacao_apuracao] <> 28
			    )
			
			VAR TotalMinutos =
			    SUMX(
			        BaseSemDuplicidade,
			        VAR Minutos =
			            'public fato_apuracao'[quantidade_horas_minutos]
			
			        VAR Sinal =
			            IF(
			                'public fato_apuracao'[flag_absenteismo] = "Sim",
			                -1,
			                1
			            )
			
			        RETURN
			            Minutos * Sinal
			    )
			
			RETURN
			    DIVIDE(TotalMinutos, 60, 0)
		lineageTag: 14caedd3-6f74-4e5b-91e4-ef20f3b981c7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '4Horas Compensação' =
			
			VAR BaseSemDuplicidade =
			    FILTER(
			        SUMMARIZE(
			            'public fato_apuracao',
			            'public fato_apuracao'[data_apuracao],
			            'public fato_apuracao'[sk_colaborador],
			            'public fato_apuracao'[cracha],
			            'public fato_apuracao'[id_situacao_apuracao],
			            'public fato_apuracao'[quantidade_horas_minutos],
			            'public fato_apuracao'[codigo_escala]
			        ),
			        'public fato_apuracao'[id_situacao_apuracao] = 28
			    )
			
			VAR TotalMinutos =
			    SUMX(
			        BaseSemDuplicidade,
			        'public fato_apuracao'[quantidade_horas_minutos]
			    )
			
			RETURN
			    DIVIDE(TotalMinutos, 60, 0)
		lineageTag: 039d6526-751e-4f0b-b855-116163f5922f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '4Horas Compensação Formatada' =
			
			VAR HorasDecimais =
			    [4Horas Compensação]
			
			VAR TotalMinutos =
			    ROUND(HorasDecimais * 60, 0)
			
			VAR Horas =
			    QUOTIENT(TotalMinutos, 60)
			
			VAR Minutos =
			    MOD(TotalMinutos, 60)
			
			RETURN
			    FORMAT(Horas, "0")
			        & "h "
			        & FORMAT(Minutos, "00")
			        & "min"
		lineageTag: 1116820c-cc6e-4afe-8d86-bf8db9194087

	measure '4Taxa Absenteísmo mês' =
			
			DIVIDE(
			    [4Horas Absenteismo],
			    [4Horas Previstas Pessoa Mês],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 482bdfba-4fbd-417d-8899-56b90b6611ee

	measure '3Horas Trabalhadas Líquidas' =
			
			VAR BaseSemDuplicidade =
			    SUMMARIZE(
			        'public fato_apuracao',
			        'public fato_apuracao'[data_apuracao],
			        'public fato_apuracao'[sk_colaborador],
			        'public fato_apuracao'[cracha],
			        'public fato_apuracao'[flag_absenteismo],
			        'public fato_apuracao'[id_situacao_apuracao],
			        'public dim_situacao_apuracao'[descricao_situacao],
			        'public fato_apuracao'[quantidade_horas_minutos],
			        'public fato_apuracao'[codigo_escala]
			    )
			
			VAR TotalMinutos =
			    SUMX(
			        BaseSemDuplicidade,
			        VAR Minutos =
			            'public fato_apuracao'[quantidade_horas_minutos]
			        VAR Sinal =
			            IF(
			                'public fato_apuracao'[flag_absenteismo] = "Sim",
			                -1,
			                1
			            )
			        RETURN
			            Minutos * Sinal
			    )
			
			RETURN
			    DIVIDE(TotalMinutos, 60, 0)
		lineageTag: 887dd04c-85aa-4c8c-a093-ac404803c733

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '4Valor Hora' =
			
			DIVIDE(
			    [4Salário Base Mensal],
			    [4Horas Previstas Pessoa Mês],
			    0
			)
		lineageTag: 32d8681a-5991-4c2b-8d73-b570bc01ef16

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '4Custo Absenteísmo' =
			
			[4Valor Hora] * [4Horas Absenteismo]
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: f81601dd-6cab-4cac-8eaf-bc548c4f0621

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Teste Ultima Data Apuracao' =
			
			MAX ( 'public fato_apuracao'[data_apuracao] )
		formatString: General Date
		lineageTag: b391efa0-e5e7-4fe5-9414-c8691a2945eb

	column sk_colaborador
		dataType: string
		lineageTag: 59704ba0-f6d1-463d-a08f-2601b60536a3
		summarizeBy: none
		sourceColumn: sk_colaborador

		annotation SummarizationSetBy = Automatic

	column data_apuracao
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: 8f6fcdaf-fd09-48e0-b1bd-3581c525bc1d
		summarizeBy: none
		sourceColumn: data_apuracao

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	column id_cod_empresa
		dataType: int64
		formatString: 0
		lineageTag: c6d2018e-af02-4911-960c-90b35c372349
		summarizeBy: sum
		sourceColumn: id_cod_empresa

		annotation SummarizationSetBy = Automatic

	column id_tipo_colaborador
		dataType: int64
		formatString: 0
		lineageTag: 3cefa8c9-e2b3-4a40-af7b-41af6de9c14e
		summarizeBy: sum
		sourceColumn: id_tipo_colaborador

		annotation SummarizationSetBy = Automatic

	column cracha
		dataType: int64
		formatString: 0
		lineageTag: 4cf76129-728e-4113-8d75-eb3877242c31
		summarizeBy: sum
		sourceColumn: cracha

		annotation SummarizationSetBy = Automatic

	column id_situacao_apuracao
		dataType: int64
		formatString: 0
		lineageTag: 6a7daa74-8fe8-475b-8ed1-143335205720
		summarizeBy: none
		sourceColumn: id_situacao_apuracao

		annotation SummarizationSetBy = Automatic

	column salario_base
		dataType: double
		lineageTag: 8213b18e-ca39-4b23-8358-9218c9834e43
		summarizeBy: sum
		sourceColumn: salario_base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column flag_absenteismo
		dataType: string
		lineageTag: ae2efc63-c169-44ce-af10-17c586acdd26
		summarizeBy: none
		sourceColumn: flag_absenteismo

		annotation SummarizationSetBy = Automatic

	column apuracao_formatada
		dataType: string
		lineageTag: ffe88142-fe7b-42f3-8ce3-78360ecd8fcf
		summarizeBy: none
		sourceColumn: apuracao_formatada

		annotation SummarizationSetBy = Automatic

	column codigo_escala
		dataType: int64
		lineageTag: e2a97c0c-a746-404d-ba04-624e26fc93ed
		summarizeBy: none
		sourceColumn: codigo_escala

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column id_centro_custo
		dataType: int64
		formatString: 0
		lineageTag: 30f647ea-8c5e-4c60-bced-9192efea4b99
		summarizeBy: none
		sourceColumn: id_centro_custo

		annotation SummarizationSetBy = Automatic

	column id_cargo
		dataType: int64
		formatString: 0
		lineageTag: 7d385fc6-1157-402b-958b-d440ad94cbca
		summarizeBy: none
		sourceColumn: id_cargo

		annotation SummarizationSetBy = Automatic

	column quantidade_horas_minutos
		dataType: int64
		formatString: 0
		lineageTag: 2a15daf8-4a5d-44a2-b862-897c0db621ab
		summarizeBy: sum
		sourceColumn: quantidade_horas_minutos

		annotation SummarizationSetBy = Automatic

	column 'Classe Afastamento > 15 dias' =
			
			VAR Situacao = 'public fato_apuracao'[id_situacao_apuracao]
			
			RETURN
			IF(
			    Situacao IN {
			        3, 6, 4, 19, 23, 53, 54, 56, 17, 108, 110, 120
			    },
			    "Afastamento > 15 dias",
			    "Outros"
			)
		lineageTag: a0a6e4f8-9937-4325-a772-4e922bb41096
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Classe Absenteísmo' =
			
			VAR Situacao = 'public fato_apuracao'[id_situacao_apuracao]
			
			RETURN
			IF(
			    Situacao IN {
			        15, 65, 135, 308, 337, 338, 150, 18, 68, 405, 415, 86, 87,
			        14, 74, 11, 61, 30, 31, 46, 47, 309, 34, 35, 20, 21, 57,
			        100, 219, 263, 208, 241, 242, 141, 144, 5, 55, 77, 115,
			        184, 279, 81, 85, 142, 143, 231, 232, 233, 234, 235, 236,
			        237, 238, 22, 342, 343, 345, 357,
			        3, 6, 4, 19, 23, 53, 54, 56, 17, 108, 110, 120
			    },
			    "Absenteísmo",
			    "Não Absenteísmo"
			)
		lineageTag: b9580258-f734-4f9e-a0a7-0b512869372b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'data_apuracao Hierarquia'
		lineageTag: 1494c6e3-f2e0-4f04-a86b-0093371bc7e8

		level data_apuracao
			lineageTag: 141c8fde-bd8d-45eb-83f0-70031765426c
			column: data_apuracao

	partition 'public fato_apuracao' = m
		mode: import
		source = let Fonte = PostgreSQL.Database("10.10.10.22", "rh_40", [CommandTimeout=#duration(0, 3, 0, 0)]), public_fato_apuracao = Fonte{[Schema="public",Item="fato_apuracao"]}[Data], #"Tipo Alterado" = Table.TransformColumnTypes(public_fato_apuracao,{{"codigo_escala", Int64.Type}, {"id_cod_empresa", Int64.Type}, {"id_tipo_colaborador", Int64.Type}, {"cracha", Int64.Type}, {"id_situacao_apuracao", Int64.Type}, {"id_cargo", Int64.Type}, {"id_centro_custo", Int64.Type}, {"quantidade_horas_minutos", Int64.Type}, {"data_apuracao", type date}}) in #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

