table 'public dim_tipo_colaborador'
	lineageTag: dbe15439-3fa3-484c-9842-4e40f8b87af8

	column id_tipo_colaborador
		dataType: int64
		formatString: 0
		lineageTag: 0e1ace6e-5b88-4bca-80c6-3c534c9bc9f3
		summarizeBy: none
		sourceColumn: id_tipo_colaborador

		annotation SummarizationSetBy = Automatic

	column descricao_tipo_colaborador
		dataType: string
		lineageTag: 8b7549fa-66a7-459d-8a7f-d18b35f72d7e
		summarizeBy: none
		sourceColumn: descricao_tipo_colaborador

		annotation SummarizationSetBy = Automatic

	partition 'public dim_tipo_colaborador' = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("10.10.10.22", "rh_40"),
				    public_dim_tipo_colaborador = Fonte{[Schema="public",Item="dim_tipo_colaborador"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(public_dim_tipo_colaborador,{{"id_tipo_colaborador", Int64.Type}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado", {"id_tipo_colaborador"})
				in
				    #"Duplicatas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

