table 'public dim_escala'
	lineageTag: 8c61b290-10b7-40a5-9d4f-89242ca91b03

	column codigo_escala
		dataType: int64
		lineageTag: 83b1b415-6b93-409e-9f43-394a155e1bbe
		summarizeBy: none
		sourceColumn: codigo_escala

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column horas_prevista_semana
		dataType: int64
		lineageTag: 61e6e51a-c771-4441-8ce5-17348053df61
		summarizeBy: none
		sourceColumn: horas_prevista_semana

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_hora_mes
		dataType: int64
		lineageTag: 28cc2f17-4f64-40a8-979f-8fa7641be304
		summarizeBy: none
		sourceColumn: total_hora_mes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column horas_prevista_semana_horas
		dataType: double
		lineageTag: 12ded7fa-88f5-45ad-9716-0528be4d63bb
		summarizeBy: none
		sourceColumn: horas_prevista_semana_horas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'public dim_escala' = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("10.10.10.22", "rh_40"),
				    public_dim_escala = Fonte{[Schema="public",Item="dim_escala"]}[Data],
				    #"Duplicatas Removidas" = Table.Distinct(public_dim_escala, {"codigo_escala"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Duplicatas Removidas",{{"horas_prevista_semana", Int64.Type}, {"total_hora_mes", Int64.Type}, {"codigo_escala", Int64.Type}}),
				    #"Coluna Horas Adicionada" = Table.AddColumn(#"Tipo Alterado", "horas_prevista_semana_horas", each [horas_prevista_semana] / 60, type number)
				in
				    #"Coluna Horas Adicionada"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

