table 'public dim_situacao'
	lineageTag: f5386076-6955-4c57-b7e6-394f10f33360

	column id_situacao
		dataType: int64
		formatString: 0
		lineageTag: b27885fb-4ebb-49df-b314-b18e179b3767
		summarizeBy: none
		sourceColumn: id_situacao

		annotation SummarizationSetBy = Automatic

	column descricao_situacao
		dataType: string
		lineageTag: db8875e4-5d9d-4969-9d42-f22bb316049c
		summarizeBy: none
		sourceColumn: descricao_situacao

		annotation SummarizationSetBy = Automatic

	partition 'public dim_situacao' = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("10.10.10.22", "rh_40"),
				    public_dim_situacao = Fonte{[Schema="public",Item="dim_situacao"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(public_dim_situacao,{{"id_situacao", Int64.Type}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado", {"id_situacao"})
				in
				    #"Duplicatas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

