table 'public dim_cargo'
	lineageTag: 9700dea8-7854-4037-9d90-6fc45dfd1df8

	column id_cargo
		dataType: int64
		formatString: 0
		lineageTag: 25ac8674-25d2-45ee-8c98-0586a31ddf3c
		summarizeBy: none
		sourceColumn: id_cargo

		annotation SummarizationSetBy = Automatic

	column descricao_cargo
		dataType: string
		lineageTag: 5dc4c44a-cecf-48df-ae14-4864b4a1525d
		summarizeBy: none
		sourceColumn: descricao_cargo

		annotation SummarizationSetBy = Automatic

	partition 'public dim_cargo' = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("10.10.10.22", "rh_40"),
				    public_dim_cargo = Fonte{[Schema="public",Item="dim_cargo"]}[Data],
				    #"Duplicatas Removidas" = Table.Distinct(public_dim_cargo, {"id_cargo"}),
				    #"Linhas Classificadas" = Table.Sort(#"Duplicatas Removidas",{{"id_cargo", Order.Descending}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Linhas Classificadas","VOLUNTARI","902",Replacer.ReplaceText,{"id_cargo"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído","ENFER","901",Replacer.ReplaceText,{"id_cargo"}),
				    #"Valor Substituído2" = Table.ReplaceValue(#"Valor Substituído1","ASSI SOCI","904",Replacer.ReplaceText,{"id_cargo"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Valor Substituído2",{{"id_cargo", Int64.Type}}),
				    #"Duplicatas Removidas1" = Table.Distinct(#"Tipo Alterado", {"id_cargo"}),
				    #"Duplicatas Removidas2" = Table.Distinct(#"Duplicatas Removidas1", {"id_cargo"})
				in
				    #"Duplicatas Removidas2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

